<a href="https://colab.research.google.com/github/Vedant-Trivedi/Experiment-14/blob/main/EXP14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 14

##Data Binning and Data formatting using python

#Vedant Trivedi - 25070123121

In [2]:
import pandas as pd
import numpy as np

data = {
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,4500],
    'Units_Sold':[25,60,35,80,50,15]
}
df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera   4500          15

In [4]:
#Data Running
bins1 = [0,20000,30000,60000]
labels1 = ['Low','Medium','High']
df['Price_Category'] = pd.cut(df['Price'],bins = bins1,labels =labels1)
print(df)

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60            Low
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera   4500          15            Low

In [6]:
#Data Running
bins2 = [0,30,60,100]
labels2 = ['Low Sales','Medium Sales','High Sales']
df['Sales_Category'] = pd.cut(df['Units_Sold'],bins = bins2,labels =labels2)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000          25           High      Low Sales
1      Mobile  20000          60            Low   Medium Sales
2      Tablet  30000          35         Medium   Medium Sales
3  Headphones   2000          80            Low     High Sales
4  Smartwatch   8000          50            Low   Medium Sales
5      Camera   4500          15            Low      Low Sales

In [8]:
#Convert data type

print(df.dtypes)

#df['Units_Sold'] = df['Units_Sold'].astype(float)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object

In [9]:
print(df.dtypes)
df['Units_Sold'] = df['Units_Sold'].astype(float)
print(df.dtypes)
df

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales_Category    category
dtype: object

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000        25.0           High      Low Sales
1      Mobile  20000        60.0            Low   Medium Sales
2      Tablet  30000        35.0         Medium   Medium Sales
3  Headphones   2000        80.0            Low     High Sales
4  Smartwatch   8000        50.0            Low   Medium Sales
5      Camera   4500        15.0            Low      Low Sales

In [11]:
#Convert Text to Uppercase
df['Product'] = df['Product'].str.upper()
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0            Low   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA   4500        15.0            Low      Low Sales

In [12]:
df['Price'] = df['Price'].round(2)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0            Low   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA   4500        15.0            Low      Low Sales

In [14]:
#Sort Data
sorted_df = df.sort_values(by='Price')
print(sorted_df)

      Product  Price  Units_Sold Price_Category Sales_Category
3  HEADPHONES   2000        80.0            Low     High Sales
5      CAMERA   4500        15.0            Low      Low Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
1      MOBILE  20000        60.0            Low   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
0      LAPTOP  55000        25.0           High      Low Sales

In [15]:
df.sort_values(by='Units_Sold', inplace=True)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
5      CAMERA   4500        15.0            Low      Low Sales
0      LAPTOP  55000        25.0           High      Low Sales
2      TABLET  30000        35.0         Medium   Medium Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
1      MOBILE  20000        60.0            Low   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales

In [16]:
df.sort_values(by='Units_Sold',ascending=False, inplace=True)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
3  HEADPHONES   2000        80.0            Low     High Sales
1      MOBILE  20000        60.0            Low   Medium Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
0      LAPTOP  55000        25.0           High      Low Sales
5      CAMERA   4500        15.0            Low      Low Sales

In [19]:
#Display Unique Values
print(df['Sales_Category'].unique())

['High Sales', 'Medium Sales', 'Low Sales']
Categories (3, object): ['Low Sales' < 'Medium Sales' < 'High Sales']

In [29]:
#Dataset: Food Delivery Orders
import pandas as pd
import numpy as np
data = {
'Order_ID': ['01', '02', '03', '04', '05', '06', '07', '08'],
'Order_Value': [250, 450, 120, 600, 300, 150, 500, 220],
'Delivery_Time': [30,45,25,60,35,20,50,28],
'Distance_km': [5,8,3,10,6,2,9,4]
}
df= pd.DataFrame(data)
df

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [31]:
#Binning Order Value

bins = [0,200,400,700]

labels = ['Low Order', 'Medium Order', 'High Order']

df['Order_Category'] = pd.cut(df['Order_Value'], bins=bins, labels=labels)

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category
0       01          250             30            5   Medium Order
1       02          450             45            8     High Order
2       03          120             25            3      Low Order
3       04          600             60           10     High Order
4       05          300             35            6   Medium Order
5       06          150             20            2      Low Order
6       07          500             50            9     High Order
7       08          220             28            4   Medium Order

In [34]:
#Binning Delivery Time

bins2 = [0,30,45,70]

labels2 = ["Fast", "Normal", "Slow"]

df['Delivery Speed'] = pd.cut(df['Delivery_Time'], bins=bins2, labels=labels2)

df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery Speed
0,01,250,30,5,Medium Order,Fast
1,02,450,45,8,High Order,Normal
2,03,120,25,3,Low Order,Fast
3,04,600,60,10,High Order,Slow
4,05,300,35,6,Medium Order,Normal
5,06,150,20,2,Low Order,Fast
6,07,500,50,9,High Order,Slow
7,08,220,28,4,Medium Order,Fast

In [37]:
# Binning Distance_km

bins_distance = [0, 4, 8, 12]

labels_distance = ["Short Distance", "Medium Distance", "Long Distance"]

df['Distance_Category'] = pd.cut(df['Distance_km'], bins=bins_distance, labels=labels_distance)

df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery Speed,Distance_Category
0,01,250,30,5,Medium Order,Fast,Medium Distance
1,02,450,45,8,High Order,Normal,Medium Distance
2,03,120,25,3,Low Order,Fast,Short Distance
3,04,600,60,10,High Order,Slow,Long Distance
4,05,300,35,6,Medium Order,Normal,Medium Distance
5,06,150,20,2,Low Order,Fast,Short Distance
6,07,500,50,9,High Order,Slow,Long Distance
7,08,220,28,4,Medium Order,Fast,Short Distance

In [40]:
# Count of categories

print(df['Order_Category'].value_counts())
df

Order_Category
Medium Order    3
High Order      3
Low Order       2
Name: count, dtype: int64

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery Speed,Distance_Category
0,01,250,30,5,Medium Order,Fast,Medium Distance
1,02,450,45,8,High Order,Normal,Medium Distance
2,03,120,25,3,Low Order,Fast,Short Distance
3,04,600,60,10,High Order,Slow,Long Distance
4,05,300,35,6,Medium Order,Normal,Medium Distance
5,06,150,20,2,Low Order,Fast,Short Distance
6,07,500,50,9,High Order,Slow,Long Distance
7,08,220,28,4,Medium Order,Fast,Short Distance